// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBblejK7xv970rBCclyK0mFwvaaZei1STg',
    appId: '1:533350667787:android:556c38341974addc80990e',
    messagingSenderId: '533350667787',
    projectId: 'uber-clone-ef1f4',
    databaseURL: 'https://uber-clone-ef1f4-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-ef1f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI1ij1-885XsOrNNNAeglVMtALs8KRXqQ',
    appId: '1:533350667787:ios:aa52506a8fddc20e80990e',
    messagingSenderId: '533350667787',
    projectId: 'uber-clone-ef1f4',
    databaseURL: 'https://uber-clone-ef1f4-default-rtdb.firebaseio.com',
    storageBucket: 'uber-clone-ef1f4.appspot.com',
    iosClientId: '533350667787-p53qj2dvmf81v00r67f9nv3l176m8nkq.apps.googleusercontent.com',
    iosBundleId: 'com.ara.usersApp',
  );
}
